.TH passkey 1 "25 June 2019" "version 1.2.0" "USER COMMANDS"
.SH NAME
passkey \- generate a cryptographic key from a passphrase
.SH SYNOPSIS
.B passkey
[\-h, \-v] [\-b] [-s salt] [passphrase]
.SH DESCRIPTION
passkey is a simple utility for generating cryptographic keys from a
passphrase using the Argon2 algorithm. Passphrases may be any string when
passed as an argument or any sequence of bytes when read from STDIN. The
program will automatically generate a fresh 128-byte salt if one is not
provided as an option. Keys are output as 64 hexadecimal characters. The salt
that was used to generate the key is output as 256 hexidecimal characters on
the subsequent line.
.SH OPTIONS
.TP
\-h, \-\-help
display help and exit
.TP
\-s, \-\-salt
provide salt as a hexidecimal string
.TP
\-v, \-\-version
output version information and exit
.SH EXAMPLES
.B passkey
"some passphrase"
.PP
.B passkey
-s 0123456789abcdef spaces in passphrases are okay too
.PP
.SH AUTHOR
Joseph Eib (github.com/stutonk)