.TH passkey 1 "14 May 2019" "version 1.1.0" "USER COMMANDS"
.SH NAME
passkey \- generate a cryptographic key from a passphrase
.SH SYNOPSIS
.B passkey
[\-h, \-v] [\-b] [-s salt] [passphrase]
.SH DESCRIPTION
passkey is a simple utility for generating cryptographic keys from a
passphrase using the Argon2 algorithm. Passphrases may be any string when
passed as an argument or any sequence of bytes when read from STDIN. The
program will automatically generate a fresh 128-byte salt if one is not
provided as an option. Keys are output as 64 hexadecimal characters (32
bytes when using binary output) prepended to the salt that was used to
generate them.
.SH OPTIONS
.TP
\-b, \-\-binary
output in binary mode
.TP
\-h, \-\-help
display help and exit
.TP
\-s, \-\-salt
provide salt as a hexidecimal string
.TP
\-v, \-\-version
output version information and exit
.SH EXAMPLES
.B passkey
"some passphrase"
.PP
.B passkey
-s 0123456789abcdef spaces in passphrases are okay too
.PP
.SH AUTHOR
Joseph Eib (github.com/stutonk)